### ISSUE TITLE
Externalize some of the constants

### ISSUE THREAD

**Issue by cchervitz** [yellowtongue/process-log-mavens#5]
It'd be really nice to externalize some of the constants used in the script (e.g., email items - subject, from, cc, smtpserver, smtpport, & the "note" used in balances.csv) in an external JSON/XML file. If no file exists, then leave as defaults as currently is now. This way, we could pull new versions down and not have to constantly edit with our own personal values.

**Comment by yellowtongue** [comment]
Agreed, This is especially true for the email settings, the roster of players, etc.

**Comment by yellowtongue** [comment]
I think the preferred way to do this would be to 
a) check for a (newly enabled) options file command line switch to pick up a set of options
b) if no option set, check for the presence of an external options file in a default specified location
c) if no option file found, use constants defined in script
d) indicate in output where the options were sourced (command line, outside file, or script)

At the very least we could start with items (b) through (d) and then get to (a) later.

**Comment by yellowtongue** [comment]
Added capability through an INI file that is by default processLogMavens.ini

For now, not enabling a command line switch to another INI file.
