### ISSUE TITLE
Skip Prior issues

### ISSUE THREAD

**Issue by yellowtongue** [yellowtongue/process-log-mavens#8]
As currently written, the --skip-prior-hands option has some issues:

- files must be passed in a specific order so that the correct hands are skipped
- skipping can only be done for one table. if files for multiple tables are passed in, only the table in the first file will get the skip logic
- there is no indication in output that any hands were skipped

I plan to address these items by moving the skip hands logic from the loop that reads in the files and forms the data structure of split hands, and instead move the skip logic to the loop that processes those split hands. 

This way the order will no longer matter, and the skip logic will apply to as many tables as are found. 

FYI @cchervitz

**Comment by yellowtongue** [comment]
New logic is in clean-hand-splitter branch

Still uses the elegant and compact approach of using the local part of the hand number, and skipping hands until local part #1 is found. 

However, the logic check is now in the loop that processes the hands, rather than in the loop that processes files. 

That means files can be passed in any order, and this logic will apply to all tables (not just the table for the first file passed in). 

Also added more detail in output to make it clear when hands were skipped.

**Comment by yellowtongue** [comment]
Merged

**Comment by cchervitz** [comment]
So cool Steve! Nicely done!!!! Can't wait to use tonight! :)

**Comment by yellowtongue** [comment]
Great, Chad, thanks!

Eager to hear. I obviously tested it myself but I had to synthesize hand
history files, as generally my group is not playing on consecutive days.

**Comment by cchervitz** [comment]
works great!

nice job!

chad
